model_path: "/home/xujg/code/UAV-VisionLoc-Deploy/model/uvl_v0807.rknn"
img_save: true
save_path: "/home/xujg/code/UAV-VisionLoc-Deploy/python/result"
img_folder: "/home/xujg/code/UAV-VisionLoc-Deploy/data/queries"
path_local_database: "/home/xujg/code/UAV-VisionLoc-Deploy/data/database/database_features.h5"
logging_level: "DEBUG" # INFO
log_path: "/home/xujg/code/UAV-VisionLoc-Deploy/python/vtl.log"
utm_zone_number: 50
utm_zone_letter: "N"
ip: "192.168.1.19"
port: 16300
camera_index: 81
output_type: "utm"  # "utm" or "lonlat"